"""
Django settings for hms_prj project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from environs import Env
env = Env()
env.read_env()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-d-x&@e5a&__rkh^26yi%gctav1mu36hj3&v(ndle1pg6+wi+fn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

SECURE_CROSS_ORIGIN_OPENER_POLICY='same-origin-allow-popups'


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'hotel',
    'userauths',
    'addon',
    'user_dashboard',
    'import_export',
    'crispy_forms',
    'mathfilters',
    'ckeditor_uploader',
    'django_ckeditor_5',
    'taggit',
    'booking',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hms_prj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hms_prj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR,'static')]
STATIC_ROOT = os.path.join(BASE_DIR,'assets')

MEDIA_URL ='/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Ensure this is correct
EMAIL_PORT = 587  # For TLS
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False  # Make sure SSL is False if using TLS
EMAIL_HOST_USER = 'mkambika287@gmail.com'  # Your email address
EMAIL_HOST_PASSWORD = 'asiachksnrqzrlbk'  # Your email password or App password
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER  # Set the default from email




# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'userauths.User'

STRIPE_SECRET_KEY=env("STRIPE_SECRET_KEY")
STRIPE_PUBLIC_KEY=env("STRIPE_PUBLIC_KEY")

LOGIN_URL = "userauths:sign-in"


JAZZMIN_SETTINGS = {
    'site_heder': 'HavenHub',
    'site_brand': 'HavenHub',
    'site_logo': 'img/hotel_logo.jpg',
    'copyright': 'HavenHub',
    'welcome_sign': 'Welcome to HavenHub',
    'topmenu_links': [
        {'name': 'Home', 'url': 'admin:index', 'permissions': ['auth.view_user']},
        {"name":"Company","url":"/admin/addon/company/"},
        {"Users":"Users","url":"/admin/userauths/user/"},
        {"model":"AUTH_USER_MODEL.User"},
    ],
    # Correctly placed custom_links
    "custom_links": {
        "hotel": [
            {
                "name": "View Visualizations",
                "url": "http://127.0.0.1:8000/visualization/",
                "icon": "fas fa-chart-bar",
                "new_window": True,
            },
            {
                "name": "Booking Summary Report",
                "url": "http://127.0.0.1:8000/reports/booking-summary/",
                "icon": "fas fa fa-file",
                "new_window": True,
            },
            {
                "name": "Revenue Report",
                "url": "http://127.0.0.1:8000/reports/revenue/",
                "icon": "fas fa fa-file",
                "new_window": True,
            },
        ]
    },
    "order_with_respect_to":[
        "hotel",
        "hotel.Hotel",
        "hotel.Room",
        "hotel.Booking",
        "hotel.BookingDetail",
        "hotel.Guest",
        "hotel.RoomServices",
        "userauths",
        "addon",
    ],
"icons": {
    "admin.LogEntry": "fas fa-file",
    "auth": "fas fa-users-cog",
    "auth.user": "fas fa-user",
    "userauths.user": "fas fa-user",
    "userauths.Profile":"fas fa-address-card",
    "hotel.Hotel":"fas fa-th",
    "hotel.Booking":"fas fa-calendar-week",
    "hotel.BookingDetail":"fas fa-calendar-alt",
    "hotel.Guest":"fas fa-users",
    "hotel.RoomServices":"fas fa-user-cog",
    "hotel.Room":"fas fa-bed",
     "hotel.Notification":"fas fa-bell",
     "hotel.Coupon":"fas fa-tag",
     "hotel.Bookmark":"fas fa-heart",
},
"show_ui_builder": True,
}



JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_small_text": False,
    "brand_colour": "navbar-indigo",
    "accent": "accent-olive",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-indigo",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger"
    }
}

EXCHANGE_RATE_API_KEY = "e4330f1da430a806e53ff470"
EXCHANGE_RATE_BASE_URL = f"https://v6.exchangerate-api.com/v6/{EXCHANGE_RATE_API_KEY}/latest/USD"
